---
- name: Install Memcached service package
  package:
    name: memcached
    state: latest
    use: apt    
  tags: [ provision ]

- name: Install Memcached service config file
  template:
    src: memcached.conf.j2
    dest: /etc/memcached.conf

- name: Is PHP-FPM installed?
  stat:
    path: '{{ memcached_php_etc_base }}/fpm/php.ini'
  register: memcached_php_fpm_ini_output
  tags: [ provision ]

- name: Install php memcached extension if PHP-FPM is present
  package:
    name: "{{ memcached_php_package }}"
    state: latest
    use: apt
  when: memcached_php_fpm_ini_output.stat.exists
  notify: 'Restart php-fpm'
  tags: [ provision ]

- meta: flush_handlers
