---
- name: Install Memcached service package
  package:
    name: memcached
    state: latest
    use: apt    
  tags: [ provision ]

- name: Install Memcached service config file
  template:
    src: memcached.conf.j2
    dest: /etc/memcached.conf

- name: Is PHP-FPM installed?
  stat:
    path: '{{ memcached_php_etc_base }}/fpm/php.ini'
  register: memcached_php_fpm_ini_output
  tags: [ provision ]

- name: Install php memcached extension if PHP-FPM is present
  package:
    name: "{{ memcached_php_package }}"
    state: latest
    use: apt
  when: memcached_php_fpm_ini_output.stat.exists
  notify: 'Restart php-fpm'
  tags: [ provision ]

- meta: flush_handlers
  when: not memcached_in_container|d(False)|bool

- name: Test if using a phusion image
  stat:
    path: "/sbin/my_init"
  register: memcached_my_init_output
  when: memcached_in_container|d(False)|bool

- name: Make sure /etc/service/memcached exists
  file:
    path: /etc/service/memcached
    state: directory
  when: memcached_in_container|d(False)|bool and memcached_my_init_output.stat.exists

- name: Install memcached at boot
  copy:
    src: memcached-init.sh
    dest: /etc/service/memcached/run
    mode: "a+x"
  when: memcached_in_container|d(False)|bool and memcached_my_init_output.stat.exists
